### ISSUE TITLE
.cmd 文件双击秒退

### ISSUE THREAD

**Issue by zhouzhendiao** [Mr-xn/kms-server-deploy#3]
我右键管理员模式之后，双击.cmd文件秒退，请问是什么原因？

**Comment by Mr-xn** [comment]
> 我右键管理员模式之后，双击.cmd文件秒退，请问是什么原因？

系统版本呢？按道理说即使没有激活也是不会闪退的

**Comment by zhouzhendiao** [comment]
> > 我右键管理员模式之后，双击.cmd文件秒退，请问是什么原因？
> 
> 系统版本呢？按道理说即使没有激活也是不会闪退的

系统是Win10专业版 19041.388
![image](https://user-images.githubusercontent.com/12294679/88786236-decd1980-d1c4-11ea-9ffd-fb555f2e68c9.png)

可能是因为教育版的原因？

**Comment by Mr-xn** [comment]
> > > 我右键管理员模式之后，双击.cmd文件秒退，请问是什么原因？
> > 
> > 
> > 系统版本呢？按道理说即使没有激活也是不会闪退的
> 
> 系统是Win10专业版 19041.388
> ![image](https://user-images.githubusercontent.com/12294679/88786236-decd1980-d1c4-11ea-9ffd-fb555f2e68c9.png)
> 
> 可能是因为教育版的原因？



> > > 我右键管理员模式之后，双击.cmd文件秒退，请问是什么原因？
> > 
> > 
> > 系统版本呢？按道理说即使没有激活也是不会闪退的
> 
> 系统是Win10专业版 19041.388
> ![image](https://user-images.githubusercontent.com/12294679/88786236-decd1980-d1c4-11ea-9ffd-fb555f2e68c9.png)
> 
> 可能是因为教育版的原因？

找到问题了 可能是下载的文件编码改变了。你下载ZIP的压缩包解压后在使用试试

**Comment by zhouzhendiao** [comment]
可以正常使用了，谢谢~

**Comment by Mr-xn** [comment]
> 可以正常使用了，谢谢~

那就行
